# Generated by Django 5.2 on 2025-04-20 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0003_alter_move_column_alter_move_row_alter_move_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
