# Generated by Django 5.2 on 2025-04-20 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0004_move_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_games', to='sudoku_api.player'),
        ),
        migrations.AddField(
            model_name='game',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
