# Generated by Django 5.2 on 2025-04-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0005_game_completed_at_game_completed_by_game_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
