# Generated by Django 5.2 on 2025-04-23 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0006_player_device_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='device_id',
        ),
    ]
