# Generated by Django 5.2 on 2025-04-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0007_remove_player_device_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'name')},
        ),
    ]
