# Generated by Django 5.2 on 2025-04-23 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0009_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('game', 'name')},
        ),
    ]
