# Generated by Django 5.2 on 2025-04-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_api', '0013_player_token_alter_player_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='Anonymous', max_length=14),
        ),
    ]
